import { SCHOOL_DAYS, type SchoolDay, type TaskTemplate } from '@lop-sach/contracts';
import { useState } from 'react';
import { Button } from '../../components/ui/Button.js';
import { eligibilityLabels, schoolDayLabels } from '../../lib/vietnamese-labels.js';
import type { TaskWriteInput } from './tasks.api.js';

export function TaskForm({ task, defaultSchoolDays, pending, onSubmit, onCancel }: { readonly task?: TaskTemplate; readonly defaultSchoolDays: readonly SchoolDay[]; readonly pending?: boolean; readonly onSubmit: (input: TaskWriteInput) => void; readonly onCancel?: () => void }): React.JSX.Element {
  const [name, setName] = useState(task?.name ?? '');
  const [schoolDays, setSchoolDays] = useState<SchoolDay[]>(task ? [...task.schoolDays] : [...defaultSchoolDays]);
  const [requiredStudents, setRequiredStudents] = useState(task?.requiredStudents ?? 1);
  const [workloadLevel, setWorkloadLevel] = useState<1 | 2 | 3 | 4>(task?.workloadLevel ?? 1);
  const [eligibilityRule, setEligibilityRule] = useState<TaskTemplate['eligibilityRule']>(task?.eligibilityRule ?? 'ANY');
  const toggleDay = (day: SchoolDay): void => setSchoolDays((current) => current.includes(day) ? current.filter((item) => item !== day) : SCHOOL_DAYS.filter((item) => [...current, day].includes(item)));
  return <form className="editor-form" onSubmit={(event) => { event.preventDefault(); onSubmit({ name: name.trim(), schoolDays, requiredStudents, workloadLevel, eligibilityRule }); }}><div className="form-grid"><div><label htmlFor="task-name">Tên công việc</label><input id="task-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={80} required /></div><div><label htmlFor="task-headcount">Số học sinh cần</label><input id="task-headcount" type="number" min={1} max={10} value={requiredStudents} onChange={(event) => setRequiredStudents(Number(event.target.value))} /></div><div><label htmlFor="task-workload">Mức công việc</label><select id="task-workload" value={workloadLevel} onChange={(event) => setWorkloadLevel(Number(event.target.value) as 1 | 2 | 3 | 4)}><option value={1}>1 · Nhẹ</option><option value={2}>2 · Vừa</option><option value={3}>3 · Nặng</option><option value={4}>4 · Rất nặng</option></select></div><div><label htmlFor="task-eligibility">Điều kiện phân công</label><select id="task-eligibility" value={eligibilityRule} onChange={(event) => setEligibilityRule(event.target.value as TaskTemplate['eligibilityRule'])}>{Object.entries(eligibilityLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div></div><fieldset><legend>Ngày thực hiện</legend><div className="choice-grid">{SCHOOL_DAYS.map((day) => <label className="check-choice" key={day}><input type="checkbox" checked={schoolDays.includes(day)} onChange={() => toggleDay(day)} />{schoolDayLabels[day]}</label>)}</div></fieldset><div className="button-row">{onCancel ? <Button variant="secondary" onClick={onCancel}>Hủy</Button> : null}<Button type="submit" disabled={pending || !name.trim() || schoolDays.length === 0 || requiredStudents < 1 || requiredStudents > 10}>{task ? 'Lưu công việc' : 'Thêm công việc'}</Button></div></form>;
}
